version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: smartcampus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smartcampus360
      MYSQL_DATABASE: smartcampus
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - campus_network

  api:
    build: ./server
    container_name: smartcampus_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: smartcampus
    networks:
      - campus_network

volumes:
  mysql_data:

networks:
  campus_network:
    driver: bridge
